ARG PYTHON_VERSION=3.12
ARG ALPINE_VERSION=3.22

#use python 3.12 - alpine as base image
FROM python:${PYTHON_VERSION}-alpine${ALPINE_VERSION}

#diable pycache
ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app
